# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: egualand <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/10 11:04:28 by egualand          #+#    #+#              #
#    Updated: 2023/08/10 13:47:21 by egualand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat
SRC = ft_cat.c

all: ${NAME}

$(NAME):
	cc -Wextra -Wall -Werror ${SRC} -o ${NAME}

clean:
	rm -f ${NAME}

fclean: clean
